### PR TITLE
Do not print empty messages.

### PR DESCRIPTION
**Pull request by robdimsdale**

### CODE REVIEW

**Comment by shalako** [comment]
Hi @robdimsdale 

Could you please provide instructions for acceptance?

**Comment by robdimsdale** [comment]
Sure, sorry, I thought I added them in the description but apparently not.

With this example `main.go`:
```
package main

import (
	"fmt"

	"github.com/cloudfoundry/multierror"
)

func main() {
	m := multierror.MultiError{}

	m.Add(fmt.Errorf("some error"))
	m.Add(fmt.Errorf("another error"))

	fmt.Println(m.Error())
}
```

Before the PR, running it gives:
```
→ go run main.go
there were 2 errors with '':
    * some error
    * another error
```

After the PR:
```
→ go run main.go
there were 2 errors:
    * some error
    * another error
```

**Comment by shalako** [comment]
Thank you, @robdimsdale 
Prioritizing for engineering review.

**Comment by shashwathi** [comment]
Thank you @robdimsdale for submitting the PR.

Regards
Shash

**Pull request merged**
